### PR TITLE
Add spcss framework (closes #25)

### LINKED ISSUE #25: New minimal style?
Just came across this which is actively developed:  https://github.com/susam/spcss

Demo:  https://susam.github.io/spcss/

Not sure if you have time. I bookmarked it, and `water` remains golden but this looks good too...

### PR DESCRIPTION
**Pull request by atusy**
@eddelbuettel
Thanks for the suggestion! I love it!!
Would you try it before merging?

As far as I tried

```r
rmarkdown::render("docs/index.Rmd")
```

and selected spcss from the UI on the page, it looks nice.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
>  it looks nice.

It sure does. Thanks for including it!   (I am a bit of a stickler so I hate scrollbars for 'overflow' in the TOC but that is just a function of the content.   Does it already support a cap on the level of sections covered in the TOC?

**Comment by atusy** [comment]
> Does it already support a cap on the level of sections covered in the TOC?

Yes, it does.

> I hate scrollbars for 'overflow' in the TOC but that is just a function of the content

What do you mean? You do not like the look and feel of the scrollbars?

**Comment by eddelbuettel** [comment]
I meant I prefer an initial look at a document not "diminished" in its visual appeal by scrollbars. So as an authors, I can control how many levels are shown (thanks for confirming that) and also ... how many words I put into each section :)

**Comment by atusy** [comment]
@eddelbuettel
Thanks for the explanation. Yes, that **was** also my milestone. I made significant improvement in #40 (merged).
The change also works with spcss.

BTW, I tweaked ToC of spcss because I do not want bullets.

I merge this PR now, but feedbacks are appreciated!

**Pull request merged**
